### PR TITLE
fix(signing):Set signing keys to never expire

### PR DESCRIPTION
**Pull request by rochacbruno**
Edited keys to never expire

No-Issue

For reference

```console
$ gpg --edit-key EBED170E8C9480E22A1D059B15250E9EC0A62577
gpg> expire
# select the option
gpg> save

# do it again for sub key
$ gpg --edit-key EBED170E8C9480E22A1D059B15250E9EC0A62577
gpg> key 1
gpg> expire
# select the option
gpg> save
```

Reexport

```console
$ gpg --armor --export EBED170E8C9480E22A1D059B15250E9EC0A62577 > dev/common/ansible-sign-pub.txt

$ gpg --output dev/common/ansible-sign-pub.gpg --armor --export EBED170E8C9480E22A1D059B15250E9EC0A62577

$ gpg --output dev/common/ansible-sign.key --armor --export-secret-keys EBED170E8C9480E22A1D059B15250E9EC0A62577
```

### CODE REVIEW

**Comment by drodowic** [comment]
The ansible-sign.key also needs to be updated in [clowd-app.yaml](https://github.com/ansible/galaxy_ng/blob/master/openshift/clowder/clowd-app.yaml#L23) by base64 encoding the file with `base64 -w0 dev/common/ansible-sign.key` so that it can be used in the ephemeral environments.

**Review by bmclaughlin — APPROVED** [review]
Fixes `Error creating signature: Unusable secret key` error in logs from expired key

**Comment by rochacbruno** [comment]
@drodowic I updated the clowder file

**Comment by jerabekjiri** [comment]
Looks like it failed on `test_namespace_management.py::test_namespace_create_and_delete[v3]` (https://github.com/ansible/galaxy_ng/actions/runs/7169599469/job/19520365056?pr=2004#step:8:1320), probably not related to this PR, but that test was recently updated in https://github.com/ansible/galaxy_ng/pull/2000 @chr-stian

**Pull request merged**
