### PR TITLE
Upgrade dev environment 

### PR DESCRIPTION
**Pull request by bmclaughlin**
Upgrades the dev environment to Python 3.8 and the base image to ubi8:8.2.
Issue: AAH-603

### CODE REVIEW

**Comment by awcrosby** [comment]
might need to update this also https://github.com/ansible/galaxy_ng/blob/f420c7bd774dd4908aaab4e18f72e5fa65549e5c/.travis.yml#L13

**Comment by bmclaughlin** [comment]
Moving to `Draft` status until [Pulp's issue for dropping Python 3.6](https://github.com/pulp/community/discussions/3) moves forward.

**Comment by awcrosby** [comment]
> Moving to Draft status until Pulp's issue for dropping Python 3.6 moves forward.

@bmclaughlin I assume pulp already supports Python 3.8, does it break things if we drop our support for Python 3.6 before they do?

**Review by himdel — APPROVED** [review]
:+1: Fixes...

```
ERROR: Package 'galaxy-ng' requires a different Python: 3.6.8 not in '>=3.8'
ERROR: Service '_base' failed to build: The command '/bin/sh -c set -ex;     pip install --no-cache-dir --editable /app     && pip install -r /app/requirements/requirements.dev.txt' returned a non-zero code: 1
```

Works for me :)

**Comment by ZitaNemeckova** [comment]
Works for me as well.

**Review by cutwater — APPROVED** [review]

**Pull request merged**
