### PR TITLE
Bump pulp_ansible to 0.23.1

### PR DESCRIPTION
**Pull request by fullsushidev**
#### What is this PR doing:

Bumping pulp_ansible version to fix FK bug found during UI tests.

Issue: [AAP-30156](https://issues.redhat.com/browse/AAP-30156)

#### Reviewers must know:

This PR should be merged only after all pipelines run green, including UI tests.

**PR Author & Reviewers**: Keep or remove backport labels per [Backporting Guidelines](https://github.com/ansible/galaxy_ng/wiki/Backporting-Guidelines)
**Reviewers**: Look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Review by jctanner — CHANGES_REQUESTED** [review]
If you change a requirement in setup.py, you also need to run `package=<packagename> make requirements/pip-upgrade-single-package` which utilizes pip-tools to recreate the requirements/requirements*.txt files that are used in container builds.

**Comment by rochacbruno** [comment]
I think we can go directly to 0.23.1

**Comment by fullsushidev** [comment]
waiting for this to be resolved: https://github.com/pulp/pulp_ansible/issues/2052

**Review by jctanner — APPROVED** [review]

**Review by jctanner — APPROVED** [review]

**Pull request merged**
