### PR TITLE
make SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL configurable

### PR DESCRIPTION
**Pull request by AndrewDi**
#### What is this PR doing:

Due to some reason, we need SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL to be configurable, the url generated by keycloak_url can not adapt to out env.

No-Issue

### CODE REVIEW

**Comment by AndrewDi** [comment]
@chambridge ptal

**Review by rochacbruno — APPROVED** [review]
LGMT 🚢 

My comments are suggestions, not blockers.

**Comment by rochacbruno** [comment]
@AndrewDi code looks good, only PR requirements needs adjusts.

1. You need to add either `Issue: AAH-xxxx` or `No-Issue` to your latest commit message (I see you have it on the PR description but CI reads from commit message)
2. If there is an issue to attach you need to also add `CHANGES/xxxx.misc` (xxxx is the issue number) with one line summaty for changelog. (if it is No-Issue the changelog is not required)

**Comment by AndrewDi** [comment]
@rochacbruno good suggestion，PTAL again

**Comment by AndrewDi** [comment]
I have compress commit into one, and add `No-Issue` to commit message, @rochacbruno PTAL

**Comment by AndrewDi** [comment]
@newswangerd @rochacbruno could you give me some help, my commit msg already have `No-Issue`, but CI still failed with 
```
INFO: Checking commit 8503b5c4 ...
ERROR: Commit 8503b5c4 has no issue attached. It must contain either 'No-Issue' or something like 'Issue: AAH-1111' which points to https://issues.redhat.com/projects/AAH project.
Error: Process completed with exit code 1.```

**Comment by newswangerd** [comment]
@AndrewDi the last requirement is that your commits need to be signed: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

The integration tests are also failing, though it doesn't look like it's related to your PR. I need to double check that.

**Comment by AndrewDi** [comment]
@newswangerd PTAL

**Review by rochacbruno — APPROVED** [review]

**Comment by AndrewDi** [comment]
@newswangerd once you fix ci，please notify me， thx

**Comment by newswangerd** [comment]
@AndrewDi ci should be working again if you want to rebase

**Comment by AndrewDi** [comment]
> @AndrewDi ci should be working again if you want to rebase

@newswangerd PTAL again

**Comment by newswangerd** [comment]
@AndrewDi your rebase was causing problems with CI, so I fixed it for you. Thanks for the contribution!

**Pull request merged**
