### PR TITLE
System auditor v3.

### PR DESCRIPTION
**Pull request by jctanner**
https://issues.redhat.com/browse/AAP-24730

replaces https://github.com/ansible/galaxy_ng/pull/2162

### CODE REVIEW

**Comment by jctanner** [comment]
unit test passed with zero permissions in the new role. Now adding just the "view" permissions already listed in app/constants.py ...

**Comment by jctanner** [comment]
With just those few permissions added, this is what the UI displays ...

image

**Comment by jctanner** [comment]
failing test passed locally ... 

`galaxy_ng/tests/integration/api/test_ui_paths.py::test_api_ui_v1_execution_environments_registries PASSED`

**Comment by jctanner** [comment]
Auditing the auditor ... 

```
# cat check_sa_access.py 
#!/usr/bin/env python

import subprocess
import requests

BASEURL = 'http://localhost:55001'
AUTH = ('sa1', 'redhat1234')
ADMIN_AUTH = ('admin', 'admin')


def get_all_routes():
    cmd = 'pulpcore-manager show_urls'
    pid = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    stdout = pid.stdout.decode('utf-8')
    lines = stdout.split('\n')
    routes = [x.strip() for x in lines if x.strip()]
    routes = [x.split('\t', 1)[0] for x in routes]
    return routes


def main():
    routes = get_all_routes()

    for route in routes:
        if '<' in route:
            continue

        url = BASEURL + route
        rr = requests.get(url, auth=AUTH)
        rr_admin = requests.get(url, auth=ADMIN_AUTH)

        if rr_admin.status_code == rr.status_code:
            continue

        print(f'MISMATCH: {url} admin:{rr_admin.status_code} auditor:{rr.status_code}')



if __name__ == "__main__":
    main()

```

```
# python3 check_sa_access.py 
MISMATCH: http://localhost:55001/ansible/collections/ admin:405 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/access_policies/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/ansible/collections/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/content/ansible/collection_marks/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/contentguards/certguard/rhsm/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/contentguards/certguard/x509/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/distributions/core/artifacts/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/exporters/core/filesystem/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/exporters/core/pulp/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/importers/core/pulp/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/importers/core/pulp/import-check/ admin:405 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/orphans/ admin:405 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/orphans/cleanup/ admin:405 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/pulp_ansible/tags/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/repair/ admin:405 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/repositories/reclaim_space/ admin:405 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/signing-services/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/task-groups/ admin:200 auditor:403
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/tasks/purge/ admin:405 auditor:500
MISMATCH: http://localhost:55001/api/galaxy/pulp/api/v3/workers/ admin:200 auditor:403
```

**Comment by jctanner** [comment]
AFAIK, this is done. Whenever someone wants to merge it, feel free.

**Review by newswangerd — APPROVED** [review]

**Pull request merged**
