### PR TITLE
Release 4.2.0

### PR DESCRIPTION
**Pull request by newswangerd**

### CODE REVIEW

**Comment by newswangerd** [comment]
Note: I'm going to update the changelog once everything is merged. For now we can use this PR as a sign off for the 4.2.0 release.

**Comment by newswangerd** [comment]
QE: Please sign off on this by end of day (5pm EST) on Thursday November 12th.
Engineering: Please sign off on this by 1pm EST on Wednesday November 11th.

**Review by ZitaNemeckova — APPROVED** [review]

**Review by awcrosby — APPROVED** [review]

**Review by bmclaughlin — APPROVED** [review]

**Review by rochacbruno — APPROVED** [review]

**Review by chouseknecht — APPROVED** [review]

**Review by alikins — APPROVED** [review]
LGTM. 
The user/group RBAC stuff makes sense and has good tests +1 
The NamespaceLink conflict stuff feels like a good way to handle that.

**Review by cutwater — APPROVED** [review]

**Review by ironfroggy — APPROVED** [review]

**Review by hendersonreed — APPROVED** [review]
:tada:

**Pull request merged**
