### PR TITLE
Update CI files

### PR DESCRIPTION
**Pull request by rochacbruno**
With this change we will stop receiving empty update CI PRs

No-Issue

### CODE REVIEW

**Review by awcrosby — APPROVED** [review]

**Comment by awcrosby** [comment]
@rochacbruno if there is a PR created by CI in galaxy_ng, does it incorporate the recent changes to the pulp plugin template?

**Comment by rochacbruno** [comment]
@awcrosby this PR has been created by the workflows/update_ci automatically.

You see my name as author because I created the token it uses to open the PRs.

We need to create a bot account, then a token with workflow access so this kinf of PR comes from the bot account.

---

This runs nightly (looks like they are changing it to be weekly) and apply any new changes done on plugin_template.

**Comment by rochacbruno** [comment]
I just figured out that the automated PR is not a signed commit, we need to see if it is possible to change it.

**Comment by awcrosby** [comment]
@rochacbruno ah ok thanks! ... _/me wonders if i am chatting with a bot right now lol_

**Pull request closed without merging**
