### PR TITLE
Allow configuration of KEYCLOAK_HOST_LOOPBACK env var

### PR DESCRIPTION
**Pull request by ironfroggy**
No-Issue

### CODE REVIEW

**Comment by ironfroggy** [comment]
I run my local-dev on a separate machine and needed this to get the auth redirects working on a specified IP address instead of the default.

**Comment by chambridge** [comment]
> I run my local-dev on a separate machine and needed this to get the auth redirects working on a specified IP address instead of the default.

I don't have a problem with this, but you should probably also add it to the `.compose.env.example` file

**Review by chambridge — CHANGES_REQUESTED** [review]
I think you need No-Issue in the commit message

**Review by chambridge — APPROVED** [review]
LGTM

**Pull request merged**
