### PR TITLE
4.4 Update pulpcore and pulp_ansible dependencies

### PR DESCRIPTION
**Pull request by bmclaughlin**
# Description 🛠
Update pulpcore (-> 3.15.4) and pulp_ansible (-> 0.10.2) dependencies and CI.
Issue: AAH-1243, AAH-1202

# Reviewer Checklists  👀
Developer reviewer:
- [ ] Code looks sound, good architectural decisions, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/)
- [ ] There is a Jira issue associated (note that "No-Issue" should be rarely used)
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed

QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)):
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed
- [ ] PR meets applicable Acceptance Criteria for associated Jira issue

Note: when merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Comment by rochacbruno** [comment]
Please rebase with master, https://github.com/ansible/galaxy_ng/pull/1106 turned deprecations test off 6 hours ago

**Comment by bmclaughlin** [comment]
Not sure if the deprecations check needs to be fixed for 4.4?  The items noted in the check may disappear in pulpcore 3.16.x but galaxy_ng 4.4.x is restricted to < 3.16.x ?

I'd be happy to check against master and fix them there if they exist?

**Comment by bmclaughlin** [comment]
@rochacbruno This PR is against 4.4 stable, can https://github.com/ansible/galaxy_ng/pull/1106 be backported to 4.4 stable?

**Review by rochacbruno — APPROVED** [review]

**Comment by mdellweg** [comment]
> @rochacbruno This PR is against 4.4 stable, can #1106 be backported to 4.4 stable? Or I can make the one-line change in `template_config.yml`? Not sure the preferred approach.

The preferred approach is to regenerate the template on the release branch. There is too much if else in the templates that a cherrypick would do the right thing with sufficient confidence.

**Review by newswangerd — APPROVED** [review]

**Review by awcrosby — APPROVED** [review]

**Review by ironfroggy — APPROVED** [review]

**Pull request merged**
