### PR TITLE
Add a new playbook to README.md on how to install galaxy_ng from a yu…

### PR DESCRIPTION
**Pull request by mikedep333**
…m package repo.

**WARNING**: This new feature for pulp_installer is still undergoing review. Variable names may change.
https://github.com/pulp/pulp_installer/pull/326

fixes: 6942
https://pulp.plan.io/issues/6942
Update galaxy_ng docs for the pulp_installer install-from-rpm support

### CODE REVIEW

**Comment by chouseknecht** [comment]
I think I would like us to remove install instructions from README, place them in the Wiki, and point users to the Wiki. Also, we don't have an RPM yet for galaxy_ng, so adding docs to galaxy_ng might be a little premature.

**Comment by mikedep333** [comment]
@chouseknecht Ack. I'll focus on getting the pulp_installer PR merged for now, so that the variable scheme won't be changed on you once the RPM repo is ready.

**Comment by mikedep333** [comment]
Once pulpcore 3.5 is released, the roles list must be changed:
```
      roles:
        - pulp_all_services
```

**Comment by mikedep333** [comment]
Per meeting discussion, the wiki / gist is here:
https://github.com/ansible/galaxy_ng/wiki/End-User-Installation

**Comment by chouseknecht** [comment]
Since install instructions moved to the wiki, think we can close this.

**Pull request closed without merging**
