### PR TITLE
Localization: Add first wave of translations for fr, ja and zh

### PR DESCRIPTION
**Pull request by rooftopcellist**
Signed-off-by: Christian M. Adams <chadams@redhat.com>

Thanks to all of the hard work from @himdel and @jerabekjiri, we now have a translated Automation Hub UI! 

Related UI Localization PR - https://github.com/ansible/ansible-hub-ui/pull/1052

Links
----------------

Related PR's
* https://github.com/ansible/galaxy_ng/pull/882
* https://github.com/ansible/galaxy_ng/wiki/l10n-guide

To check this out for yourself, stand up the galaxy_ng & ansible-hub-ui dev environment, navigate to it in the browser, and select a different language in your browser settings.  Then refresh the page.

### CODE REVIEW

**Comment by himdel** [comment]
Hm, I may be missing something here but I can't get these to work...
@rooftopcellist @jerabekjiri any idea what?

```
galaxy_ng/app/api/v3/viewsets/namespace.py
67:                detail={'name': _('A namespace named %s already exists.') % name}
68-            )
69-        return super().create(request, *args, **kwargs)
```

:+1: correctly marked for translation

```
galaxy_ng/locale/fr/LC_MESSAGES/django.po
232:msgid "A namespace named %s already exists."
233-msgstr "Un espace de nom nommé %s existe déjà."
```

:+1: correctly translated



:+1: correct request & response language headers



:crying_cat_face: the message is still English

---

I tried running `pulpcore-manager compilemessages` manually (maybe not the easiest way but it did run)...

```
docker exec -it galaxy_ng_api_1 bash
mkdir /home/galaxy/bin
cd /home/galaxy/bin

cat > msgfmt <<EOF
#!/bin/sh
export LD_LIBRARY_PATH=/home/galaxy/bin
msgfmt_ "$@"
EOF

scp my_machine:/bin/msgfmt msgfmt_
scp my_machine:/usr/lib/x86_64-linux-gnu/libgettext* .

pulpcore-manager compilemessages
```

but it doesn't seem to help.

**Comment by rochacbruno** [comment]
@rooftopcellist you need to add one of `No-Issue` or `Issue: AAH-xxx` to your commit message.

**Comment by rooftopcellist** [comment]
One of these days I'll get that right on the first try, thanks @rochacbruno , I just updated with a change note.

**Comment by rooftopcellist** [comment]
@himdel I think this PR is ready to go now.

**Pull request merged**
