### PR TITLE
Update to galaxy-importer==0.3.4

### PR DESCRIPTION
**Pull request by awcrosby**
No-Issue

### CODE REVIEW

**Review by rochacbruno — APPROVED** [review]

**Comment by awcrosby** [comment]
CI is now fixed. @rochacbruno could you re-review? I changed approach here: I updated to galaxy-importer==0.3.4 in setup.py and ran `pip-compile` for each requirements.txt file.

I did not run `make requirements` since this would update all requirements including pulpcore and it would not allow for backport per [guidelines](https://github.com/ansible/galaxy_ng/wiki/Backporting-Guidelines)

**Review by rochacbruno — APPROVED** [review]

**Pull request merged**
