### PR TITLE
Update remote rh-certified default url

### PR DESCRIPTION
**Pull request by drodowic**
#### What is this PR doing:

* Updates the remote rh-certified default url

AAP-15623

#### Reviewers must know:

**PR Author & Reviewers**: Keep or remove backport labels per [Backporting Guidelines](https://github.com/ansible/galaxy_ng/wiki/Backporting-Guidelines)
**Reviewers**: Look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Review by jctanner — APPROVED** [review]

**Comment by jctanner** [comment]
Are we backporting this or should those labels be removed?

**Review by jctanner — CHANGES_REQUESTED** [review]
If a system has already run this migration, it won't run it again if the file changed.  I think it'd be better to make a new migration file which is sure to be run.

**Comment by drodowic** [comment]
> If a system has already run this migration, it won't run it again if the file changed. I think it'd be better to make a new migration file which is sure to be run.

The intent in modifying an existing migration is so that only new installations will get the updated URL so that we don't impact customers who might have already modified it.

**Comment by jctanner** [comment]
> > If a system has already run this migration, it won't run it again if the file changed. I think it'd be better to make a new migration file which is sure to be run.
> 
> The intent in modifying an existing migration is so that only new installations will get the updated URL so that we don't impact customers who might have already modified it.

A new migration file can do a conditional update by checking the current value.

**Comment by jctanner** [comment]
With the new migration file, we can remove the change in the old file right? Also, should the backport labels be removed?

**Review by jctanner — APPROVED** [review]

**Pull request merged**
