### PR TITLE
fix openapi spec

### PR DESCRIPTION
**Pull request by jctanner**
# Description 🛠
https://issues.redhat.com/browse/AAH-1169

# Reviewer Checklists  👀
Developer reviewer:
- [ ] Code looks sound, good architectural decisions, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/)
- [ ] There is a Jira issue associated (note that "No-Issue" should be rarely used)
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed

QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)):
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed
- [ ] PR meets applicable Acceptance Criteria for associated Jira issue

Note: when merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Comment by jctanner** [comment]
[openapi.json.txt](https://github.com/ansible/galaxy_ng/files/8125389/openapi.json.txt)

**Review by newswangerd — APPROVED** [review]

**Review by awcrosby — DISMISSED** [review]
Want to pause merging this until discussion with pulp over maintaining compatibility with pulp bindings

**Review by fao89 — COMMENTED** [review]
Adding back the PREPROCESSING_HOOKS would have a very similar effect to this PR https://github.com/ansible/galaxy_ng/pull/710

IIRC correctly @alikins removed it because it was breaking the galaxy post-installation with squeezer

**Comment by awcrosby** [comment]
@jctanner has this been rebased since #1148 was merged?

**Pull request merged**
