### PR TITLE
Update to galaxy-importer 0.3.4

### PR DESCRIPTION
**Pull request by awcrosby**
Updating only galaxy-importer on stable-4.3, not any other dependencies.

### CODE REVIEW

**Comment by rochacbruno** [comment]
@awcrosby CI is `Docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.`

**Comment by rochacbruno** [comment]
@awcrosby I tried to rebuild manually on travis but still erroring, can you try rebasing

**Review by rochacbruno — CHANGES_REQUESTED** [review]
CI is failing, might need a rebase

**Comment by awcrosby** [comment]
@rochacbruno i think the fail is due to a python3.8 update in a pulp image that needs to be updated in the `stable-*` branches, i will remove you as reviewer until i make that fix, thanks!

**Review by rochacbruno — APPROVED** [review]

**Pull request merged**
