### PR TITLE
galaxy_collection folder 

### PR DESCRIPTION
**Pull request by Dule-martins**
#### What is this PR doing:

This PR resolves the issue  with number #318 found in the ansible-community / community-team repo

Issue: AAH-2420

#### Reviewers must know:

**PR Author & Reviewers**: Keep or remove backport labels per [Backporting Guidelines](https://github.com/ansible/galaxy_ng/wiki/Backporting-Guidelines)
**Reviewers**: Look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Comment by Dule-martins** [comment]
@oraNod can you help with this, I would love to get this out of the way

**Comment by samccann** [comment]
@Dule-martins - thanks for your patience here as we work through an unfamiliar workflow.  The CI is now failing because of : 
ERROR: Missing change log entry for issue AAH-2420.

Looking at the [Contributor guide](https://github.com/ansible/galaxy_ng/wiki/Contributing#preparing-pull-requests) It looks like we can avoid adding a changelog here if you amend the commit message to use `Partial-Issue` instead of `Issue`. Can you give that a try please? Remember the Partial-Issue has to be on its own line, separate from the rest of the commit message.   I can't recall if you did this in the last commit or not? If not, I think the format is 
`git commit --amend -m "Galaxy collection folders" -m "Partial-Issue: AAH-2420"`

**Comment by Dule-martins** [comment]
Thank you @samccann I will take a look at it again and again until I succeed at it! Thanks for replying

**Comment by Dule-martins** [comment]
> @Dule-martins - thanks for your patience here as we work through an unfamiliar workflow. The CI is now failing because of : ERROR: Missing change log entry for issue [AAH-2420](https://issues.redhat.com/browse/AAH-2420).
> 
> Looking at the [Contributor guide](https://github.com/ansible/galaxy_ng/wiki/Contributing#preparing-pull-requests) It looks like we can avoid adding a changelog here if you amend the commit message to use `Partial-Issue` instead of `Issue`. Can you give that a try please? Remember the Partial-Issue has to be on its own line, separate from the rest of the commit message. I can't recall if you did this in the last commit or not? If not, I think the format is `git commit --amend -m "Galaxy collection folders" -m "Partial-Issue: AAH-2420"`

Hello @samccann As you can see I tried to follow your instructions but we still have a failed Galaxy CI. I went through the error log and found out that the `ERROR: Missing change log entry for issue AAH-2420`. and 
`Error: Process completed with exit code 1`. 

After going through the contributors' guide I noticed that a commit that references one or multiple issues must have a change log. In our case how can I identify the change log so I could add it to the commit message since that is what is missing?

**Comment by rochacbruno** [comment]
HEy, either you put `No-Issue` in the commit message or please add a file on CHANGES/ directory

```bash
echo "add skeleton for galaxy_collection docs" > CHANGES/2420.doc
```

https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/dev/getting_started/#submitting-a-pull-request

**Pull request merged**
