### PR TITLE
Bump pulpcore to 3.28.7 for httpdownloader+async fix.

### PR DESCRIPTION
**Pull request by jctanner**

### CODE REVIEW

**Comment by jctanner** [comment]
actually, we need a 3.28.6 for the httpdownloader fix.

**Comment by EamonTracey** [comment]
Can we unskip the ee registry test? https://github.com/ansible/galaxy_ng/blob/0a9fab159c8d34bfc610f2506a5e3eda8943e539/galaxy_ng/tests/integration/api/test_ui_paths.py#L236C11-L236C11

**Review by EamonTracey — APPROVED** [review]
Awesome 👍

**Comment by jctanner** [comment]
https://github.com/ansible/galaxy_ng/pull/1822

**Pull request merged**
