### PR TITLE
Update to pulpcore 3.15, pulp_ansible 0.10, pulp_container 2.8.0

### PR DESCRIPTION
**Pull request by rochacbruno**
- Fix deprecation query for pulpcore compatibility (Deprecation is now a
  content)
- Add migration to alter user first name size (added by Django 3.1 core
  change)
- Fixed LANGUAGE_CODES on settings as required by Django 3+
- Created database encryption key on the docker base image for
  development only.
- Generated the requirements files.

Issue: AAH-707

### CODE REVIEW

**Comment by fao89** [comment]
pulp-ansible 0.10.0 is released!

**Comment by rochacbruno** [comment]
@cutwater I rebased with your changes #918  but still failing

**Comment by newswangerd** [comment]
@rochacbruno since we're updating drf access policy, we also need to do this: https://issues.redhat.com/browse/AAH-789

Mind taking care of that in this PR? It's a quick fix

**Review by newswangerd — APPROVED** [review]

**Pull request merged**
