### PR TITLE
Wrapper script for functional testing

### PR DESCRIPTION
**Pull request by jctanner**
# Description 🛠
Fix for functional tests and helper script for running local similar to CI

# Reviewer Checklists  👀
Developer reviewer:
- [ ] Code looks sound, good architectural decisions, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/)
- [ ] There is a Jira issue associated (note that "No-Issue" should be rarely used)
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed

QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)):
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed
- [ ] PR meets applicable Acceptance Criteria for associated Jira issue

Note: when merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Review by rochacbruno — APPROVED** [review]
So this is to be used when running with vagrant based dev environment? do we need something for when our dev environment is the one based on docker-compose?

**Comment by jctanner** [comment]
@rochacbruno this allows me to run the functional tests locally in the same way that they are run with CI, so the baseline is an ubuntu 20.04 machine to match the azure workers in github actions... I included the example vagrantfile for anyone to use as a reference.

-If- we plan to run integration tests against a standalone stack with docker-compose, I may do something similar for that as well but it won't be as important since our makefile and compose scripts wrap everything up very nicely.

**Review by awcrosby — COMMENTED** [review]
if we can confirm the `.ci/` files are not overwritten on running pulp plugin_template, or changes are added to pulp plugin_template (if needed)... then LGTM

**Comment by rochacbruno** [comment]
needs rebase

**Pull request closed without merging**
