### PR TITLE
Fix missing ansible-importer configuration

### PR DESCRIPTION
**Pull request by cutwater**
No-Issue

### CODE REVIEW

**Comment by cutwater** [comment]
@jameswnl With this fix that requires adding the NAMESPACE parameter, we can move Route to the OpenShift template as well.

**Review by awcrosby — APPROVED** [review]

**Comment by jameswnl** [comment]
As commented in slack, just a reminder:  `ConfigMap` needed to be in `managedResources` section in deploy-clowder.yml in app-int

**Review by jameswnl — APPROVED** [review]

**Pull request merged**
