### PR TITLE
Rename `permissions_assignment` to `creation_hooks`

### PR DESCRIPTION
**Pull request by fao89**
Ref: https://github.com/pulp/pulpcore/pull/1627

### CODE REVIEW

**Review by bmbouter — COMMENTED** [review]
This looks right to me. @mdellweg wdyt?

**Review by awcrosby — APPROVED** [review]

**Review by bmclaughlin — APPROVED** [review]

**Comment by fao89** [comment]
Could it be merged?

**Comment by rochacbruno** [comment]
2 approvals I am going yo merge

**Pull request merged**
