### PR TITLE
Add git commit to api root, populated via crc pipeline

### PR DESCRIPTION
**Pull request by awcrosby**
Issue: AAH-1360

# Description 🛠
Add git commit to api root, populated via crc pipeline

# Reviewer Checklists  👀
Developer reviewer:
- [ ] Code looks sound, good architectural decisions, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/)
- [ ] There is a Jira issue associated (note that "No-Issue" should be rarely used)
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed

QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)):
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed
- [ ] PR meets applicable Acceptance Criteria for associated Jira issue

Note: when merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Review by drodowic — APPROVED** [review]

**Comment by jctanner** [comment]
I know the commit should reveal most things, but could we add the branch too? HEAD on one branch could reflect the same commit as master but not include -every- commit on master.

**Pull request merged**
