### PR TITLE
Add Keys, Script and Signing Service to dev environment

### PR DESCRIPTION
**Pull request by rochacbruno**
This PR adds the following features

- [x] Dev environment GPG keys
- [x] Dev environment Signing Script
- [x] Dev environment Signing Service creation
- [x] (the same as above for Github CI test runs)
- [x] Settings variables for signing configuration
- [x] Auto sign on collection approval
- [x] endpoints to perform on-demand signing
- [x] signatures exposed on v3/collection/ endpoint (for CLI)
- [x] signatures and sign states exposed on ui/v1/ endpoints (for UI)
- [x] settings and feature flags exposed on /settings/ and /feature-flags/ (for UI)
- [x] permissions exposed on /me/ (for UI)
- [x] Filtering by sign state (for UI endpoint)
- [x] Logging for collection signatures
- [x] Setup Signing Service on ephemeral (by @drodowic ) 
- [ ] Functional testing for collection signatures
- [x] Sync `signed_only` content field on Remote configuration

## metadata

Issue: AAH-1181
env:LOCK_REQUIREMENTS=0
env:PULP_ANSIBLE_REVISION=main

### CODE REVIEW

**Comment by rochacbruno** [comment]
```bash
Collection Version
GET /api/automation-hub/content/published/v3/collections/tosigntest/tosignf/versions/1.0.0/
HTTP 200 OK
Allow: GET, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
```
```json
{
    "version": "1.0.0",
    "href": "/api/automation-hub/content/published/v3/collections/tosigntest/tosignf/versions/1.0.0/",
    "created_at": "2021-12-16T18:43:21.748529Z",
    "updated_at": "2021-12-16T18:43:21.748551Z",
    "requires_ansible": ">=2",
    "artifact": {
        "filename": "tosigntest-tosignf-1.0.0.tar.gz",
        "sha256": "cd5eb8b5c089dbfff708b37b2bbbe60741fa0cedcb65a5a32ba9674306a74ac3",
        "size": 1574
    },
    "collection": {
        "id": "044ef4c9-7df4-4465-aedb-36c82d97095f",
        "name": "tosignf",
        "href": "/api/automation-hub/content/published/v3/collections/tosigntest/tosignf/"
    },
    "download_url": "http://localhost:5001/api/automation-hub/v3/artifacts/collections/published/tosigntest-tosignf-1.0.0.tar.gz",
    "name": "tosignf",
    "namespace": {
        "name": "tosigntest"
    },
    "signatures": [
        {
            "signature": "-----BEGIN PGP SIGNATURE-----\n\niQHIBAABCAAyFiEE6+0XDoyUgOIqHQWbFSUOnsCmJXcFAmHAbQ0UHGdhbGF4eTNA\nYW5zaWJsZS5jb20ACgkQFSUOnsCmJXdtkwv8DtivdZQwGkD3yg7dCspqyHQJ3lDV\nh4sXLwoabgx25QFBP9Oo+wb55HdZcWUiAzyU2LjW9vDH+8qWExWdYY00WpX3t1ln\n3vVRd6ki6VBip6/5+UwHYzstm4eimgqeo1OYDeiGuZugam0tGggElj1wMS04UkCE\ngNBN8N7LfI3zu2U6YywB0GYX6DYRwCdiAu/BwpJQMiNF4kX0eT8Xtjvp4OyGWRAg\njIDfuQ38VXBmUGuO/0G2pNyHJjliWtKUtagdB7hdr5RbiFeJfxgCTDx8pwGRuOJU\n1syO4+ohcnU3OVqg0lCheDdmna56Iy6sNKoTHrTfeMk/xJn5e7L7fWf6LWjfu++v\nA8JsIrcU3ncBgVa/mcxq/SxAZ+DX+ioLE46VIrSvgabZcwUHjhl4EcABeTs/2xxJ\ndTNfauhLIDCx77zs07kwkwvUmawMAItkb+Q82FRiQKIctpj2Y0VZ/6dORpov2bQ6\nOUoWLAiPl8H+W/D329/V1wiZv/Cu5NTDdN5A\n=luz7\n-----END PGP SIGNATURE-----\n",
            "pubkey_fingerprint": "EBED170E8C9480E22A1D059B15250E9EC0A62577"
        }
    ],
    "metadata": {
        "authors": [
            "Orion User 1"
        ],
        "contents": [],
        "dependencies": {
            "tosigntest.tosignh": "<=3.0.0"
        },
        "description": "a collection with some deps on other collections",
        "documentation": "",
        "homepage": "",
        "issues": "",
        "license": [
            "GPL-3.0-or-later"
        ],
        "repository": "http://github.example.com/orionuser1/skeleton",
        "tags": [
            "collectiontest"
        ]
    },
    "manifest": {},
    "files": {}
}
```

**Comment by rochacbruno** [comment]
URL to sign collection on demand

```bash
curl -X POST \
  'http://0.0.0.0:8002/api/automation-hub/v3/sign/collections/' \
  -H 'Accept: */*' \
  -H 'Authorization: Token a64a0ab93948c92febf2c0611dc1b189f9f37cdd' \
  -H 'Content-Type: application/json' \
  -d '{
    "signing_service": "ansible-default",
    "repository": "published",
    "namespace": "bla",
    "collection": "zaz",
    "version": "1.5.0",
    "content_units": ["*"]
}'
```

URL (POST ONLY)
```bash
http://0.0.0.0:8002/api/automation-hub/v3/sign/collections/
```

Payloads

**Required**
```json
{
    "signing_service": "ansible-default",
    "repository": "published",
}
```

Either `content_units` is specified (* or a list of UUIDS)

```json
{
    "signing_service": "ansible-default",
    "repository": "published",
    "content_units": ["*"]
}
```
OR sign all `collections` and `versions` under a `namespace`

```json
{
    "signing_service": "ansible-default",
    "repository": "published",
    "namespace": "bla",
}
```

sign all  versions under a specific collection

```json
{
    "signing_service": "ansible-default",
    "repository": "published",
    "namespace": "bla",
    "collection": "zaz",
}
```

Sign specific by version specifier

```json
{
    "signing_service": "ansible-default",
    "repository": "published",
    "namespace": "bla",
    "collection": "zaz",
    "version": "1.2.3"
}
```

**Comment by rochacbruno** [comment]
Added to `_ui/v1` APIs

http://0.0.0.0:5001/api/automation-hub/_ui/v1/collection-versions/?limit=2

Signed collection versions gets a `signatures` field, this field exposes the fingerprint for the pub_key used in the signature, the SIGNATURE is available only on the `v3/` API.

```json
"data": [
    {
      "namespace": "test",
      "name": "a",
      "version": "1.0.0",
      "requires_ansible": ">=2",
      "created_at": "2022-01-14T14:04:02.157731Z",
      "metadata": {
        "dependencies": {
          "test.b": "*"
        },
        "contents": [],
        "documentation": "",
        "homepage": "",
        "issues": "",
        "repository": "http://github.example.com/orionuser1/skeleton",
        "description": "a collection with some deps on other collections",
        "authors": [
          "Orion User 1"
        ],
        "license": [
          "GPL-3.0-or-later"
        ],
        "tags": [
          "collectiontest"
        ],
        "signatures": [
          "EBED170E8C9480E22A1D059B15250E9EC0A62577"
        ]
      },
      "contents": [],
      "repository_list": [
        "published"
      ]
    }
```


On `http://0.0.0.0:5001/api/automation-hub/_ui/v1/repo/published/?deprecated=false`

There is now 2 fields, the same `signatures` as above and also a `sign_state`

```json
"data": [
    {
      "id": "5e094530-4439-4188-9f83-6c278583d981",
      "namespace": {
        "id": 1,
        "name": "test",
        "company": "",
        "email": "",
        "avatar_url": "",
        "description": "",
        "groups": [
          {
            "id": 1,
            "name": "system:partner-engineers",
            "object_permissions": [
              "upload_to_namespace",
              "change_namespace",
              "delete_namespace"
            ]
          }
        ]
      },
      "name": "a",
      "download_count": 0,
      "latest_version": {
        "namespace": "test",
        "name": "a",
        "version": "1.0.0",
        "requires_ansible": ">=2",
        "created_at": "2022-01-14T14:04:02.157731Z",
        "metadata": {
          "dependencies": {
            "test.b": "*"
          },
          "contents": [],
          "documentation": "",
          "homepage": "",
          "issues": "",
          "repository": "http://github.example.com/orionuser1/skeleton",
          "description": "a collection with some deps on other collections",
          "authors": [
            "Orion User 1"
          ],
          "license": [
            "GPL-3.0-or-later"
          ],
          "tags": [
            "collectiontest"
          ],
          "signatures": [
            "EBED170E8C9480E22A1D059B15250E9EC0A62577"
          ]
        },
        "contents": []
      },
      "deprecated": false,
      "sign_state": "signed"
    }
```

Values are:

- unsigned: collection doesn't at least one version signed.
- signed: collection has all versions signed.
- partial: collection has some versions signed.

c/c @himdel

**Comment by himdel** [comment]
Hey, checking the necessary endpoints, I think we're missing a couple:

* namespace detail / collection list:
  * [x] `_ui/v1/repo/published/` (= `CollectionAPI.list`) - items have `.sign_state`
    * :red_circle: is always `partial` now, despite the only available versions having been uploaded the same way, after signatures enabled
  * [ ] filtering in `_ui/v1/repo/published/` by sign state
  * [ ] sign all collections can *probably* use the same endpoint to get the count, filtering for sign_state IN partial,unsigned with limit=1 and using meta.count (needs filtering)

* collection detail
  * [x] `_ui/v1/repo/published/:namespace/:collection/` (= `CollectionAPI.getCached`) - `.latest_version.metadata.signatures`
    * :warning: this is enough if we're only showing signed state for the currently selected version - we would need a `sign_state` + `all_versions[*].signature` combo to
      * indicate a partically signed collection (some versions yes some no)
      * show sign state in the version selector
      * be able to disable the Sign all button
      * count the number of affected versions for Sign all
    * :question: is it possible to get multiple signatures in the array? Would we display all of them?
    * :red_circle: is always an empty array now
  * [x] `_ui/v1/collection-versions/?namespace=...&name=...&repository=...` (= `CollectionVersionAPI.list` with a `name` + `namespace` + `repository` filter - not used yet)
    * this can be used if we don't add this to `all_versions` above, at the cost of a second API request that downloads the contents of all versions, and needs disabled pagination to really get all versions (though it may already be disabled there, couldn't get ?limit=1 to affect my 2 items)
    * [x] sign all versions can use this one to get the count

* [ ] approval dashboard (TODO me ..still updating this comment..)
* [ ] feature exposed (TODO me)


> the `SIGNATURE DATA` hash is available only on the v3/ API

I'm not sure what you mean, is that the hash in the signatures array?
Or is that some other hash the UI would want to consume? (And if so, which v3 api? :))

**Comment by rochacbruno** [comment]
@brumik 

```json
{
  "id": "f006b2b0-e044-4e0f-b167-8c169f0a6d4d",
  "namespace": {
    "id": 5,
    "name": "vittest",
    "company": "",
    "email": "",
    "avatar_url": "",
    "description": "",
    "groups": [
      {
        "id": 1,
        "name": "system:partner-engineers",
        "object_permissions": [
          "upload_to_namespace",
          "change_namespace",
          "delete_namespace"
        ]
      }
    ]
  },
  "name": "vith",
  "download_count": 0,
  "latest_version": {
    "namespace": "vittest",
    "name": "vith",
    "version": "4.0.0",
    "requires_ansible": ">=2",
    "created_at": "2022-01-24T17:04:33.344202Z",
    "metadata": {
      "dependencies": {},
      "contents": [],
      "documentation": "",
      "homepage": "",
      "issues": "",
      "repository": "http://github.example.com/orionuser1/skeleton",
      "description": "a collection with some deps on other collections",
      "authors": [
        "Orion User 1"
      ],
      "license": [
        "GPL-3.0-or-later"
      ],
      "tags": [
        "collectiontest"
      ],
      "signatures": []
    },
    "contents": [],
    "version_sign_state": "unsigned",
    "docs_blob": {
      "contents": [],
      "collection_readme": {
        "html": "<p>This is collection_reqs_test collection</p>",
        "name": "README.md"
      },
      "documentation_files": []
    }
  },
  "all_versions": [
    {
      "version": "4.0.0",
      "created": "2022-01-24 17:04:33.344202+00:00",
      "version_sign_state": "unsigned"
    },
    {
      "version": "3.0.0",
      "created": "2022-01-24 17:04:32.851448+00:00",
      "version_sign_state": "unsigned"
    },
    {
      "version": "2.0.0",
      "created": "2022-01-24 17:04:32.366363+00:00",
      "version_sign_state": "unsigned"
    },
    {
      "version": "1.0.0",
      "created": "2022-01-24 17:04:31.887908+00:00",
      "version_sign_state": "signed"
    }
  ],
  "sign_state": "partial",
  "total_versions": 4,
  "signed_versions": 1,
  "unsigned_versions": 3
}
```

and

```json
{
  "id": "bd1f6b5c-cf75-4752-af08-c37ec166d38d",
  "namespace": {
    "id": 5,
    "name": "vittest",
    "company": "",
    "email": "",
    "avatar_url": "",
    "description": "",
    "groups": [
      {
        "id": 1,
        "name": "system:partner-engineers",
        "object_permissions": [
          "upload_to_namespace",
          "change_namespace",
          "delete_namespace"
        ]
      }
    ]
  },
  "name": "vith",
  "download_count": 0,
  "latest_version": {
    "namespace": "vittest",
    "name": "vith",
    "version": "5.0.0",
    "requires_ansible": ">=2",
    "created_at": "2022-01-24T17:04:33.904249Z",
    "metadata": {
      "dependencies": {},
      "contents": [],
      "documentation": "",
      "homepage": "",
      "issues": "",
      "repository": "http://github.example.com/orionuser1/skeleton",
      "description": "a collection with some deps on other collections",
      "authors": [
        "Orion User 1"
      ],
      "license": [
        "GPL-3.0-or-later"
      ],
      "tags": [
        "collectiontest"
      ],
      "signatures": [
        {
          "signature": "-----BEGIN PGP SIGNATURE-----\n\niQHIBAABCAAyFiEE6+0XDoyUgOIqHQWbFSUOnsCmJXcFAmHu3C8UHGdhbGF4eTNA\nYW5zaWJsZS5jb20ACgkQFSUOnsCmJXeCBwv+KRukj6gRuNxfx+buJvqztzFkNdQz\nm9M/nrAKrLZngOgYBE1oAw4wH9vrcayDay/WvOF3ESgZLBdP1pMTWam403zXHESL\nEzOK3SkikHw2kh2tnBO+3yimLf0EhPNBYbp9CGw4zQ0BhloKqwRODAIr5iOT3L0y\nB1dp6l7MvS068dbtLnHYaEpm7XYcnVH+mewHcmpcTwli6DPoTU7ff82fbunMRT1W\n3KiRjMeEbRqgMC9QazXTU9MREYQ5CSxBR8uCekKJRKw6bij5bX5LHj4KFy2HA2PI\nRDFdy+ir6cqaJgfmr2tfAN4c6dzUnxLDMmZvuywrbw3qnYaGjOUGHZbl3DFaG9Zp\no60dnseIhPjFaHeFfydV6IyaehGml5Http1gdv60e7qbBsto1CbEKigI5BNfqJTu\nRp9Cz34lbZLpSNZnq/XUMqsuqNcCP1mze4g5Xq6AvT98TG27jN3zPyMb+0dmkN+A\n21GAOPFzAjnFhoQp0LwrheTLYbMeRrg9qkPz\n=ZQbE\n-----END PGP SIGNATURE-----\n",
          "pubkey_fingerprint": "EBED170E8C9480E22A1D059B15250E9EC0A62577",
          "signing_service": "ansible-default"
        }
      ]
    },
    "contents": [],
    "version_sign_state": "signed",
    "docs_blob": {
      "contents": [],
      "collection_readme": {
        "html": "<p>This is collection_reqs_test collection</p>",
        "name": "README.md"
      },
      "documentation_files": []
    }
  },
  "all_versions": [
    {
      "version": "5.0.0",
      "created": "2022-01-24 17:04:33.904249+00:00",
      "version_sign_state": "signed"
    }
  ],
  "sign_state": "signed",
  "total_versions": 1,
  "signed_versions": 1,
  "unsigned_versions": 0
}
```

**Comment by rochacbruno** [comment]
How to determine if the system has signing enabled?

/api/automation-hub/_ui/v1/feature-flags/
```json
{
  "collection_auto_sign": true,
  "collection_signing": true,
  "execution_environments": true
}
```

Or by checking on:

/api/automation-hub/_ui/v1/settings/

```json
"GALAXY_COLLECTION_SIGNING_SERVICE": "ansible-default",
"GALAXY_AUTO_SIGN_COLLECTIONS": true
```

**Comment by rochacbruno** [comment]
Permissions on http://0.0.0.0:5001/api/automation-hub/_ui/v1/me/

```json
"model_permissions": {
    "sign_collections_on_namespace": true,
    "sign_collections_on_repository": true,
```

on approval dashboard the permission is `"move_collection": true,` as if user can move the sign is automatic

**Comment by rochacbruno** [comment]
AppSre PR Check will fail until we get pulp_ansible released and requirements updated here on the PR.

On Github CI there is the `env:PULP_ANSIBLE_REVISION=main` that is applied to the CI container, this setting is not used by the APPSre container image.

The failure will be this until we get (pulp_ansible release OR appsre to use `PULP_ANSIBLE_REVISION` + `LOCK_REQUIREMENTS` variables)

```
19:14:56   File "/app/galaxy_ng/app/tasks/signing.py", line 3, in <module>
19:14:56     from pulp_ansible.app.tasks.signature import sign
19:14:56 ModuleNotFoundError: No module named 'pulp_ansible.app.tasks.signature'
```

c/c @drodowic

**Comment by rochacbruno** [comment]
Aditional info:

we can expose the public key for downloading (Not sure yet where) using this API

http://0.0.0.0:5001/pulp/api/v3/signing-services/?name=ansible-default

```json
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "pulp_href": "/pulp/api/v3/signing-services/0ccb79ca-5c99-4227-9143-8902f1e1af1c/",
      "pulp_created": "2022-01-14T13:43:31.263540Z",
      "name": "ansible-default",
      "public_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQGNBGGyPsgBDACpWO2BexH3orSI2ksseqLjQ9h6Eq2HaBQdJLLQZZvkiWB/e3Gy\n8gvO3wgP7XxcIH09kddvmEFa4BXheXNd74qKTdoKh5UX2oFnw1rDwrQjcMKxJnjm\nYku6br68kMfaNkwyQrSY7wwZ3XG/UfoWtdMehZKDZWD1YwTuaSJ5kxhsmQVxlN+U\npTMG3uEC7aykogyzIH2PWvMoaP+XDvUb7XXJs0Z54tPzF9ngYpNiwTlMrm7+Q2FG\n1qognKlzEfKJ9FVSE9cO7MGCYOYCUrKcPahEMMnNDRnY5FwCEVTZhH/LgXg0pY7x\npyKAvCFi+j2QSlYlvhGKJWgZG2v9qH6DPRla5mf8+f6/gviEGum9DwwjlJ2bFWrw\nfVGH7Ij9L1D3qjxFuMJkumEF9qpdfG8NZYingDsbgwjdKn6VXqmdVkUXNDwnk3gG\ntPQ9wd46qrUPzjwJ+66c28XKnjOJbJ7HU1bth9q7uvnoOqgNJGJVJhX+1+CXhSIA\nUnPsTOq5ivx/2DUAEQEAAbQiR2FsYXh5IERldiAzIDxnYWxheHkzQGFuc2libGUu\nY29tPokB1AQTAQgAPhYhBOvtFw6MlIDiKh0FmxUlDp7ApiV3BQJhsj7IAhsDBQkD\nwmcABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEBUlDp7ApiV3i0UL/1mjlc08\nIHJDA64xIqifN96s7TEpuSw1DNkCrvBpZkbcZjEpLYW8QiTatTUbf2NgEFlOl6Xi\nH1Q9+oU03BAF1e8ymTRFuCkPdhqcjbkORke5/1PuemGG39SfRVsjVNrceXh9kWs0\neOfnOvDt4RpNUO2lHf34NmQuxRqiALSb4gK5xrS2K2Y2hySEZldy6RcGURdm+pmf\no4XQIZuzlGo7bV1vEmfZ/81kkOS5FlmOZt+Qm+YB8B7VjGY1RLtH7kY0y75j9Xea\nXMeraK+g3Om5TkCsqryR5EMs+xlX2B20rmVJ4NIxkq8o+llr3Yac/+T261XMjHGr\n2Sg/mVHVKTqtLlRwNDfg+iAQsr9AuUe4azp1EFAZL7zVQaFGlDRo1FX4EyTiVi7j\nnSNWl5j3Jm2+n7ddG7qi1v8OYxMFwtJoGeqLI3QFCu7la/hQVg8M7bifeMx4O9/G\nw4Q2EemGGMhSuC3p8Wig0sUIxu84xTHBGttFdwGimNS+pEd5LjTgwbulcrkBjQRh\nsj7IAQwArHLjcJTMfDuxOLF6cVprf7eidcC5YMKf5zIp2kRHLJdLGC2IbvLPcegM\ns9qh/GAfpO+3MbdUycoTJF7QrFxXqilJPbSEgQQN7J+SKjQ2UE95GxjSAijZ7moo\na87crV/wvk+qth0XZCF3flKGJ2KQHIWN/9R6hRiPRjSy8KAHpxgjpEIjdhz4emPr\naRzyK9zOqXWymcnTO2LcEP5NdBK8QIEXg7XYO2k7i08okhMzA+u0+Ke2ZDT/pI1e\nwd+xnBwpGoycQvVNSJg8bG5rPhWD9ADiR0SB+r12fLmReQBF/wVG9rB7pW3F3KqU\nm7CjgC3mP9EuqbDA2G4ruH1+T4Ff1zbaXmB5BzRu+VgRoQ50m6j84IJvq1kKAn5E\nUbRn6583ltgNPid9dzmslCN7upuzzq2fV7PRWCKcd0aT/wJ94UBO4ufjo8hIFwxa\nRbSAruBRJfWsS9rDwYs32QwfmSLrDXYlGpjG1HUZ3J5LLjHipvZeZlmNt5rUvni/\najQcyiP5ABEBAAGJAbwEGAEIACYWIQTr7RcOjJSA4iodBZsVJQ6ewKYldwUCYbI+\nyAIbDAUJA8JnAAAKCRAVJQ6ewKYldz/uC/9JiVlWge5sswUYUiV+TcXtATN3UKRE\nBEKtQYNgBW6geLwMyIsxSTBfpSoioezSZrriFirnQAtvrygUqTeX/uq4TD5qY502\nEejE+onF7bHpUEfJ/biyXQuFDBqNGBsWYnXxPbhXBY+mGhY5un5mg6TEGL2SMdSj\n5uhTBcaQ3BkGaqNng1nVC710nwQcMm8f9qs4uOogqy7Ndl1xtoRQZa9/Vbi3vIDC\nP9GYGUdAPu1OuXvl9wFYIKlWy95CS+L25o/59JbqT+XLLiyAnEmyMvWF+JUScm6H\n6wAjDoZOenmBSzgKs/7POb7z3ktZrEWvTcNHWCuH7hwYOP/zAWrble9RdUsRZF/K\ndcWrMZmkDSqOch6Qbp+vc8n/Z1rFiNvyfbiAkQ/Z9BW3+iHolEGHwq4i/O9Xx5bq\nNWuRMs3XgtmQpAxFi2C8nGo5E8eDUw4qKHXYNkcuOraay0wBNpoffISO4+d24GB4\nI6KUd9Bv1wf+etJ50jZ0dzt+T1Qs2wKbtf0=\n=PHJy\n-----END PGP PUBLIC KEY BLOCK-----\n",
      "pubkey_fingerprint": "EBED170E8C9480E22A1D059B15250E9EC0A62577",
      "script": "/var/lib/pulp/scripts/collection_sign.sh"
    }
  ]
}
```

**Comment by brumik** [comment]
@rochacbruno Can we please rename the `version_sign_state` to `sign_state`. The `version_` prefix is obsolete since it is under a `all_versions` or `latest_version` entry.

**Comment by rochacbruno** [comment]
@brumik @himdel this PR is being replaced by https://github.com/ansible/galaxy_ng/pull/1145

**Pull request closed without merging**
