### PR TITLE
Localization stable-4.5 string update

### PR DESCRIPTION
**Pull request by rooftopcellist**
# Description 🛠

Localization Update from 4-19 push.  Soon to follow, the translated strings from the 4-19 push.

### CODE REVIEW

**Comment by rooftopcellist** [comment]
This PR has all of the changes https://github.com/ansible/galaxy_ng/pull/1244 does and more, so the old PR can be closed now.

**Comment by rooftopcellist** [comment]
cc @himdel for review

**Review by newswangerd — CHANGES_REQUESTED** [review]
Can you open this against master instead?

**Comment by rooftopcellist** [comment]
@newswangerd In the future, to catch any string changes between stable-4.5 and master, I will push strings for both master and the stable branch.  Memsource pre-fills translations when new strings are pushed, so these changes will be picked up for the master branch on the next push/pull cycle (and make it into stable-4.6).  

^^ just for context.  I will target the master branch, that way we get these strings merged there earlier.

**Review by newswangerd — APPROVED** [review]

**Comment by himdel** [comment]
(maybe close and open will wake github up...)

**Pull request merged**
