### PR TITLE
Update translations automatically  

### PR DESCRIPTION
**Pull request by jerabekjiri**
Issue: AAH-2265

Automate running `django-admin makemessages --all`, ` django-admin compilemessages` and committing translation files weekly.
         

Solution taken from https://github.com/ansible/ansible-hub-ui/blob/master/.github/workflows/i18n.yml

### CODE REVIEW

**Comment by himdel** [comment]
Looks good! :)

2 potential issues:

* django makemessages will try to match new strings and add fuzzy translations .. which will cause linter issues when the untranslated text does interpolation but the "matching" translation doesn't, or vice versa
  * pretty much what happened in https://github.com/ansible/galaxy_ng/pull/1659
  * I guess the easy version is just to run the perl script from there before compiling the updated translations (after makemessages but before compilemessages)
  * alternatively, `msgattrib --clear-fuzzy --empty -o /path/to/output.po /path/to/input.po` (from the `gettext` apt package) should *probably* do the same thing (https://code.djangoproject.com/ticket/10852, https://stackoverflow.com/questions/7372414/removing-all-fuzzy-entries-of-a-po-file)

* git push *might* trigger some branch protection rules here and fail, I know we had to change ui repo settings for this to work .. but merging is probably the only way to know for sure :)

**Comment by jerabekjiri** [comment]
@himdel I thought of fuzzy matching, weird that it doesn't generate/add any fuzzy strings when running  `django-admin makemessages` locally. I'll test it more

**Comment by himdel** [comment]
Try adding new strings, it only does that if the string is not already in the pot file. (And it has to be similar enough to an existing string.)

**Comment by jerabekjiri** [comment]
> Try adding new strings, it only does that if the string is not already in the pot file. (And it has to be similar enough to an existing string.) .. or you can try reverting https://github.com/ansible/galaxy_ng/pull/1659 locally and trying again

reverting worked, thanks :) 

Added `msgattrib --clear-fuzzy` script for every language folder

**Review by himdel — APPROVED** [review]

**Comment by jerabekjiri** [comment]
Merging this, so it can be tested.

**Pull request merged**
