### PR TITLE
playbooks for CI checks, units and functional tests

### PR DESCRIPTION
**Pull request by jctanner**
This is a set of playbooks, roles, files and templates that are able to spawn a container almost identical to the one generated by https://github.com/pulp/plugin_template 's scripts and then run the various checks, unit tests and functional tests. All without needing to use the files layed out by https://github.com/pulp/plugin_template 

Key differences with these playbooks:
* can be run locally on any x86 linux or macos machine with docker
* set the python version on the container from the earliest step in the process
* can install projects in editable mode for live edit&debug loops
* coverage reporting on the unit tests
* we can edit and improve them without having to use the plugin template repo

### CODE REVIEW

**Comment by himdel** [comment]
Guessing this has some dependencies?

```
~/galaxy_ng$ dev/playbooks/RUNALL.sh 
dev/playbooks/RUNALL.sh: line 5: docker-killall: command not found
```

Also, how will this interact with a running oci-env on the same machine?

**Comment by jctanner** [comment]
@himdel that's just a helper script i run locally that i didn't mean to commit

**Comment by himdel** [comment]
Ah :) but the intended way to run this is still

```
cd dev/playbook
ANSIBLE="ansible-playbook -i 'localhost,' --forks=1 -vvvv"
$ANSIBLE build_container.yaml
$ANSIBLE start_container.yaml
$ANSIBLE run_unit_tests.yaml
```

?

`build_container` fails for me...

```
TASK [Build pulp image] ********************************************************
task path: /home/himdel/galaxy_ng/dev/playbooks/build_container.yaml:28
error checking context: no permission to read from '/home/himdel/.local/share/containers/storage/vfs/dir/1183ed2bc46f217d716f66eba51a744c1f92ebd202537314f2bfcf1ee1dc6da7/etc/gshadow'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "Command 'docker build --network host --no-cache=False -t pulp:ci_build -f /home/himdel/galaxy_ng/dev/playbooks//cache/Containerfile ../../..' returned non-zero exit status 1.",
    "msg": "Command execution failed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by jctanner** [comment]
@himdel try nesting the checkout under a directory like /home/himdel/src/ ...

The mount config for the container is going to mount the parent directory of the galaxy_ng checkout to /src inside the container so that it can do editable installs of adjacent projects.

**Review by himdel — APPROVED** [review]
Works for me :+1: 

```
mkdir ~/src
cd ~/src
git clone git@github.com:ansible/galaxy_ng.git
cd galaxy_ng/
# git fetch origin pull/2079/head && git checkout FETCH_HEAD && git checkout -b pr2079
cd dev/playbooks/
ANSIBLE="ansible-playbook -i 'localhost,' --forks=1 -vvvv"
$ANSIBLE build_container.yaml
$ANSIBLE start_container.yaml
$ANSIBLE run_unit_tests.yaml
```

```
=========== 177 passed, 25 skipped, 11 warnings in 84.25s (0:01:24) ============
```

**Review by bmclaughlin — APPROVED** [review]
Looks good to me.  :+1: 

Unit tests:
=========== 179 passed, 25 skipped, 11 warnings in 73.25s (0:01:13) ============

Functional tests:
============ 7 passed, 2 skipped, 242 warnings in 90.62s (0:01:30) =============

**Review by rochacbruno — APPROVED** [review]

**Pull request merged**
