### PR TITLE
Update tests to use ~/.ansible.cfg rather than /ansible.cfg

### PR DESCRIPTION
**Pull request by mikedep333**
This fixes the tests when used in the dev env.

No-Issue

### CODE REVIEW

**Comment by mikedep333** [comment]
@dkliban fyi, if you were developing a workaround for this in oci_env, you no longer need to.

**Comment by alikins** [comment]
Presumably the before case, the tests were looking for ansible.cfg in CWD.

As far as I can tell, that is normally https://github.com/ansible/galaxy_ng/blob/master/ansible.cfg

It looks like that only exists to setup ansible tmp_dirs for use with ansible-importer. If importer tests work I guess it doesn't matter ?

**Comment by jctanner** [comment]
deprecated by https://github.com/ansible/galaxy_ng/pull/2305

**Pull request closed without merging**
