### PR TITLE
Remove errant pytest mark

### PR DESCRIPTION
**Pull request by bmclaughlin**
#### What is this PR doing:
Removes a pytest mark, currently throwing warnings in CI,  that I missed removing in a previous PR.

No-Issue

#### Notes: 

**PR Author**: Add a QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)); 
**Reviewers**: look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

### CODE REVIEW

**Review by awcrosby — APPROVED** [review]
LGTM but i think you will need to rebase to get the 3 pulp ci jobs to pass

**Comment by awcrosby** [comment]
@bmclaughlin if this errant mark exists in either stable-4.6 or stable-4.5, can you add the backport labels the PR?

**Comment by bmclaughlin** [comment]
@awcrosby, the PR that introduced it, #1462, was not backported (also manually checked both stable-4.5 and stable-4.6 to be sure).

**Pull request merged**
